server:
  rootPath: /api
redis:
  type: basic
  name: my-tournament
  node:
    type: redis
    node: "redis_server:6379"
    clientName: tournament-app
  redisCodec:
    type: string
  clientResources:
    type: default
    commandLatencyCollector:
      type: default
      enabled: false